# Generated by Django 5.0.6 on 2024-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=100)),
                ('employee_department', models.PositiveIntegerField()),
                ('salary', models.PositiveIntegerField()),
                ('job', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
